{% set version = "0.7.3" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-params
  version: {{ version|replace("-", "_") }}

source:
  fn: params_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/params_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/params/params_{{ version }}.tar.gz
  sha256: b2d90477b85cdc4ace643fdee5c92820ad58659b800a8bfd36e40bfaba4d317e

build:
  noarch: generic
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-whisker

  run:
    - r-base
    - r-whisker

test:
  commands:
    - $R -e "library('params')"  # [not win]
    - "\"%R%\" -e \"library('params')\""  # [win]

about:
  home: https://github.com/sahilseth/params
  license: GPL-2.0-only
  summary: An interface to simplify organizing parameters used in a package, using external configuration files. This attempts to provide a cleaner alternative to options().
  license_family: GPL2

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
