{% set version = "0.7.7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-params
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/params_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/params/params_{{ version }}.tar.gz
  sha256: 6397aac3b638d352de443ae2684e1ce9b6ae72b55f64efb233b20b63f5e626cb

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpptoml
    - r-glue
    - r-purrr
    - r-readr >=1.4.0
    - r-whisker
  run:
    - r-base
    - r-rcpptoml
    - r-glue
    - r-purrr
    - r-readr >=1.4.0
    - r-whisker

test:
  commands:
    - $R -e "library('params')"  # [not win]
    - "\"%R%\" -e \"library('params')\""  # [win]

about:
  home: https://github.com/sahilseth/params
  license: GPL-2.0-only
  summary: An interface to simplify organizing parameters used in a package, using external configuration files. This attempts to provide a cleaner alternative to options().
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
