appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Y86hrLXX7w3zPR9d8yUr8vmEdHyoWfRHTQEKFHYC2r/Js6exl9I8eSJxsmBaSpzYVvFKrcLPPQfwKkOv0EfJq1gHjhbci/0/LtaNumo2m9vSKmF+Y4/B0r6Kr05xvOy42pGibnXYi0By1Naa7kvSAFwcp3U6Jv73tiDmWIcAnwAFWTlIqUkqVH1xuznXx1thaTQ2V3ZWXtR+paMt67bdvQxzjuOwq3dhdc2Fj9AJihVRlXSThsvtvNx2jluQSrU7SZWPbKWprxnqCtaFWxTJzGaFp6mNqeqAdGQmlgSGyMR7BD2D53QZZBcgzEPyyBobVEdfdAcNo41cjNYH3ia2veIP0QcuLKT1eGwQUGTDkbnTW5oipllsy9RlQRSSy7ZAf5UI+eHq67gn8ucyQlLDc3hT3r5YV+VdIo7it4KDpOz7MiCqv6/wEDd1mbvERgjGNv5gTVbgJ572A7W7FZVJV9r4QZRUCfnaqif5fruGJqtFNtvFY8MyOXNJ+fRBkMZ2QpNJnhqRyhzhgIa7vEl7T/ALsoD/I96GmO9BIsVWCjb+eILPaSBgef54IGUNHROnR5NXO82QKs7B8xjF8Keu5aHUwWuFtSALlZl+EzHWjrRK1SeW1XPfffV0djI4x5q4qsqhup2zYkslnNWl2ssGr7lvVzyhDVjpfO/AtqU0ybo=}
